// Bounded desktop/mobile audit of 0.2 workflows, synthetic media only.
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, openSync, closeSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { chromium } from 'playwright-core';
import { browserPath } from '../src/server/browser.mjs';
import { writeWavMono16 } from '../src/vocal/wav.mjs';
import { createFixtureProject, fixtureScene } from './tests/feedback/helpers.mjs';
import { freePort } from './tests/helpers/free-port.mjs';

const root=fileURLToPath(new URL('..',import.meta.url));
const out=mkdtempSync(join(root,'.cache/release020-ui-'));
const projects=join(out,'projects'),uiPort=await freePort(),port=await freePort();
const origin=`http://127.0.0.1:${uiPort}`,base=`http://127.0.0.1:${port}`;
Object.assign(process.env,{VIDEOGRAPH_PROJECTS:projects,VIDEOGRAPH_SERVICE_PORT:String(port),VIDEOGRAPH_SERVICE_TOKEN_FILE:join(out,'token'),VIDEOGRAPH_STUDIO_ORIGINS:origin,VITE_VIDEOGRAPH_SERVICE_URL:base});
const id=createFixtureProject(projects,{name:'0.2 界面隔离验收'}),dir=join(projects,id);
mkdirSync(join(dir,'engine/audio'),{recursive:true});
mkdirSync(join(dir,'engine/docs'),{recursive:true});
writeFileSync(join(dir,'engine/docs/ENGINE.md'),'Synthetic canvas fixture; no WebGL. UI/protocol audit only.');
const backing=join(dir,'engine/audio/song.wav'),dry=join(out,'dry.wav');
writeWavMono16(backing,new Float32Array(44100*8));
writeWavMono16(dry,Float32Array.from({length:44100*4},(_,i)=>Math.sin(i*2*Math.PI*440/44100)*.12));
const db=new DatabaseSync(join(dir,'project.sqlite'));
const project=JSON.parse(db.prepare('SELECT data FROM project').get().data);
project.audio={name:'synthetic.wav',hash:createHash('sha256').update(readFileSync(backing)).digest('hex'),engineFile:'audio/song.wav'};
db.prepare('UPDATE project SET data=?').run(JSON.stringify(project));db.close();
const {submitSceneModule}=await import('../src/server/project-store.mjs');
submitSceneModule(id,'shared',0,fixtureScene(90),project.shots.map(s=>({shotId:s.id,expectedInputRevision:0})),'隔离共享场景','human');
const {createProjectService}=await import('../src/server/service.mjs');
const service=createProjectService(),log=openSync(join(out,'vite.log'),'w');
let ui,browser;
const errors=[],overflow=[];
try{
  await service.start();
  ui=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port',String(uiPort),'--strictPort'],{cwd:root,env:process.env,windowsHide:true,stdio:['ignore',log,log]});
  for(let i=0;i<100;i++){try{if((await fetch(origin)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch({headless:true,executablePath:browserPath()});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${origin}/?view=project&project=${id}`);
  await page.getByRole('button',{name:'查看 / 修改真实源码'}).click();
  await page.getByRole('dialog').waitFor();
  assert.equal(await page.getByRole('button',{name:'提交给全部 2 个共用镜头'}).isVisible(),true);
  await page.getByRole('button',{name:'预览草稿',exact:true}).click();
  await page.getByTitle('未提交的场景草稿').waitFor();
  await page.screenshot({path:join(out,'source-desktop.png')});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:join(out,'source-mobile.png')});
  overflow.push(await page.evaluate(()=>({surface:'source',width:innerWidth,scroll:document.documentElement.scrollWidth})));
  await page.getByRole('button',{name:'关闭源码'}).click();
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('.vocal-panel > summary').click();
  await page.getByText('导入 MIDI 或外部人声',{exact:true}).click();
  await page.getByLabel('外部人声干轨路径',{exact:true}).fill(dry);
  await page.getByLabel('参考人声路径（可选）',{exact:true}).fill(dry);
  await page.getByRole('button',{name:'保存外部人声草稿',exact:true}).click();
  await page.getByText('已保存外部干轨，下一步渲染候选混音。',{exact:true}).waitFor();
  await page.getByRole('button',{name:'渲染歌声',exact:true}).click();
  await page.getByRole('button',{name:'采用此混音',exact:true}).waitFor({timeout:60000});
  await page.getByText('人声干轨与文件',{exact:true}).click();
  const link=page.getByRole('link',{name:'频段能量对比 JSON',exact:true});
  assert.equal((await fetch(await link.getAttribute('href'))).ok,true);
  await page.locator('.vocal-panel').screenshot({path:join(out,'vocal-desktop.png')});
  await page.setViewportSize({width:390,height:844});
  await page.locator('.vocal-panel').screenshot({path:join(out,'vocal-mobile.png')});
  overflow.push(await page.evaluate(()=>({surface:'vocal',width:innerWidth,scroll:document.documentElement.scrollWidth})));
  const result={projectId:id,out,uiErrors:errors,overflow,sharedSource:true,draftPreview:true,externalImport:true,bandDownload:true};
  writeFileSync(join(out,'report.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
  assert.deepEqual(errors,[]);assert.ok(overflow.every(v=>v.scroll<=v.width));
}finally{await browser?.close();ui?.kill();await service.close();closeSync(log);}
